permalink: /:title

title: zhangqi的博客
url: http://zhangqi.life
feed: /atom.xml
author_info: <a href="http://zhangqi.life">zhangqi</a>

theme: jekyll-theme-architect

links1 :
  - name : 所有1
    url   : /
    type  : recent1
    external : false
  - name  : 数据结构
    url:  /blog/数据结构
    type: data_struct
    external: false

blog_1 : recent
blog_2 : 数据结构
